import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import * as finance from './financeApi';
import type {Dashboard,Expense,Subscription,Asset,ExpenseCategory} from './types';
const message=(e:unknown)=>{const v=e as {response?:{data?:{error?:{details?:Record<string,string[]>;message?:string}}};friendlyMessage?:string};return Object.values(v.response?.data?.error?.details??{}).flat()[0]??v.response?.data?.error?.message??v.friendlyMessage??'Request failed';};
export function FinancePage(){
 const [params]=useSearchParams(),documentId=Number(params.get('document_id'))||null;
 const [tab,setTab]=useState<'dashboard'|'expenses'|'subscriptions'|'assets'|'receipt'>((documentId?'receipt':'dashboard'));
 const [overview,setOverview]=useState<Dashboard|null>(null),[items,setItems]=useState<Expense[]>([]),[subs,setSubs]=useState<Subscription[]>([]),[goods,setGoods]=useState<Asset[]>([]),[categories,setCategories]=useState<ExpenseCategory[]>([]),[insights,setInsights]=useState<Awaited<ReturnType<typeof finance.subscriptionInsights>>|null>(null);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[month,setMonth]=useState(new Date().toISOString().slice(0,7));
 const [expense,setExpense]=useState({title:'',amount:'',currency:'LKR',expense_date:new Date().toISOString().slice(0,10),merchant_name:'',expense_category_id:'',recurrence_cycle:'',description:'',document_id:''});
 const [sub,setSub]=useState({name:'',provider:'',price:'',currency:'LKR',billing_cycle:'monthly',next_billing_date:'',renewal_type:'automatic',cancellation_deadline:''});
 const [asset,setAsset]=useState({name:'',brand:'',model:'',serial_number:'',purchase_date:'',purchase_price:'',currency:'LKR',location:''});
 const [suggestion,setSuggestion]=useState<Awaited<ReturnType<typeof finance.receiptSuggestion>>|null>(null);
 async function refresh(){try{const [d,e,s,a,c,i]=await Promise.all([finance.dashboard(month),finance.expenses(),finance.subscriptions(),finance.assets(),finance.getCategories(),finance.subscriptionInsights()]);setOverview(d);setItems(e);setSubs(s);setGoods(a.assets);setCategories(c.categories);setInsights(i);setError('');}catch(e){setError(message(e));}}
 useEffect(()=>{void refresh();},[month]);
 useEffect(()=>{if(documentId)void finance.receiptSuggestion(documentId).then(setSuggestion).catch(e=>setError(message(e)));},[documentId]);
 async function act(p:Promise<unknown>,ok='Saved'){try{await p;setNotice(ok);setError('');await refresh();}catch(e){setError(message(e));}}
 const safe=(v:Record<string,string>)=>Object.fromEntries(Object.entries(v).filter(([,value])=>value!=='' ).map(([k,value])=>[k,/^(document_id|expense_category_id)$/.test(k)?Number(value):value]));
 return <main className="page"><header><div><h1>LifePilot Finance</h1><p>P5 · Expenses, subscriptions, assets and warranties</p></div><div className="actions"><Link className="button-link secondary" to="/tasks">Tasks</Link><Link className="button-link secondary" to="/documents">Documents</Link><Link className="button-link secondary" to="/">Dashboard</Link></div></header>
 <nav className="finance-tabs">{(['dashboard','expenses','subscriptions','assets','receipt'] as const).map(t=><button key={t} className={tab===t?'':'secondary'} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</nav>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}
 {tab==='dashboard'&&<section className="card"><h2>Monthly overview</h2><label>Month <input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div className="finance-cards"><article><h3>Monthly spending (by currency)</h3>{overview?.monthly_totals.map(t=><p key={t.currency}><strong>{t.currency} {t.total}</strong></p>)}</article><article><h3>Monthly subscription estimates</h3>{Object.entries(overview?.monthly_subscription_cost_by_currency??{}).map(([c,v])=><p key={c}>{c} {v.toFixed(2)}</p>)}</article><article><h3>Subscriptions due (30 days)</h3>{overview?.subscriptions_due.map(s=><p key={s.id}>{s.name}: {s.next_billing_date}</p>)}</article><article><h3>Warranties expiring</h3>{overview?.warranties_expiring.map(w=><p key={w.id}>{w.asset?.name}: {w.end_date}</p>)}</article><article><h3>Merchant totals</h3>{overview?.merchant_totals.map((m,i)=><p key={i}>{m.merchant?.name??'Unspecified'}: {m.currency} {m.total}</p>)}</article><article><h3>Recent purchases</h3>{overview?.recent_purchases.map(a=><p key={a.id}>{a.name}</p>)}</article></div><p className="finance-muted">{overview?.asset_value_placeholder.note}</p></section>}
 {tab==='expenses'&&<section className="card"><h2>Expenses</h2><div className="actions"><button type="button" className="secondary" onClick={()=>{const name=prompt('New expense category');if(name)void act(finance.saveCategory(name),'Category created');}}>Add category / budget placeholder</button></div><form className="finance-form" onSubmit={e=>{e.preventDefault();void act(finance.createExpense(safe(expense)),'Expense recorded');}}>{(['title','amount','currency','expense_date','merchant_name','description','document_id'] as const).map(k=><label key={k}>{k.replaceAll('_',' ')}<input type={k==='amount'||k==='document_id'?'number':k==='expense_date'?'date':'text'} value={expense[k]} onChange={e=>setExpense(v=>({...v,[k]:e.target.value}))} required={['title','amount','currency','expense_date'].includes(k)}/></label>)}<label>Category<select value={expense.expense_category_id} onChange={e=>setExpense(v=>({...v,expense_category_id:e.target.value}))}><option value="">Uncategorized</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Repeat<select value={expense.recurrence_cycle} onChange={e=>setExpense(v=>({...v,recurrence_cycle:e.target.value}))}>{['','daily','weekly','monthly','quarterly','yearly'].map(v=><option value={v} key={v}>{v||'None'}</option>)}</select></label><button type="submit">Record expense</button></form><div className="actions"><button className="secondary" onClick={()=>void finance.exportCsv().catch(e=>setError(message(e)))}>Export CSV</button><label className="button-label">Import CSV<input style={{display:'none'}} type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)void act(finance.importCsv(f),'CSV imported');}}/></label></div><h3>Recorded expenses</h3>{items.map(x=><article className="finance-row" key={x.id}><div><b>{x.title}</b><small>{x.expense_date} · {x.merchant?.name??'No merchant'} · {x.source}</small>{x.document_id&&<Link to={`/documents?document_id=${x.document_id}`}>Source document #{x.document_id}</Link>}</div><strong>{x.currency} {x.amount}</strong><div className="actions">{x.recurrence_cycle&&<button className="secondary" onClick={()=>void act(finance.confirmRecurring(x.id),'Next recurring occurrence confirmed')}>Confirm next {x.next_occurrence_date}</button>}<button className="secondary" onClick={()=>{const title=prompt('Expense title',x.title);if(title)void act(finance.updateExpense(x.id,{title}),'Expense updated');}}>Rename</button><button className="danger" onClick={()=>{if(confirm('Delete this expense?'))void act(finance.deleteExpense(x.id),'Expense deleted');}}>Delete</button></div></article>)}</section>}
 {tab==='subscriptions'&&<section className="card"><h2>Subscriptions</h2><form className="finance-form" onSubmit={e=>{e.preventDefault();void act(finance.createSubscription(safe(sub)),'Subscription saved');}}>{(['name','provider','price','currency','next_billing_date','cancellation_deadline'] as const).map(k=><label key={k}>{k.replaceAll('_',' ')}<input type={k.includes('date')||k==='cancellation_deadline'?'date':k==='price'?'number':'text'} step={k==='price'?'0.01':undefined} required={['name','provider','price','currency','next_billing_date'].includes(k)} value={sub[k]} onChange={e=>setSub(v=>({...v,[k]:e.target.value}))}/></label>)}<label>Billing cycle<select value={sub.billing_cycle} onChange={e=>setSub(v=>({...v,billing_cycle:e.target.value}))}>{['daily','weekly','monthly','quarterly','yearly'].map(c=><option key={c}>{c}</option>)}</select></label><label>Renewal type<select value={sub.renewal_type} onChange={e=>setSub(v=>({...v,renewal_type:e.target.value}))}><option value="automatic">Automatic</option><option value="manual">Manual</option></select></label><button>Track subscription</button></form>{subs.map(s=><article className="finance-row" key={s.id}><div><b>{s.name}</b><small>{s.provider} · {s.billing_cycle} · next {s.next_billing_date}</small>{s.previous_price&&<small>Earlier price: {s.previous_price}</small>}</div><strong>{s.currency} {s.price}</strong><div className="actions"><button className="secondary" onClick={()=>{const amount=prompt('Confirmed payment amount',s.price);if(amount)void act(finance.recordPayment(s.id,{amount,billing_date:new Date().toISOString().slice(0,10)}),'Payment recorded');}}>Record paid amount</button><button className="secondary" onClick={()=>{const price=prompt('Updated price',s.price);if(price)void act(finance.updateSubscription(s.id,{price}),'Subscription price updated');}}>Change price</button><button className="danger" onClick={()=>{if(confirm('Stop tracking? This does NOT cancel the provider subscription.'))void act(finance.cancelTracking(s.id),'Tracking stopped only');}}>Stop tracking</button></div></article>)}<h3>Insights</h3>{insights?.recurring_charge_candidates.map((x,i)=><p key={i}>Possible recurring expense: {x.merchant?.name} ({x.occurrence_count} charges). Review manually.</p>)}</section>}
 {tab==='assets'&&<section className="card"><h2>Assets</h2><div className="actions"><button type="button" className="secondary" onClick={()=>{const name=prompt('Asset category');if(name)void act(finance.addAssetCategory(name),'Asset category saved');}}>Add asset category</button></div><form className="finance-form" onSubmit={e=>{e.preventDefault();void act(finance.addAsset(safe(asset)),'Asset saved');}}>{(['name','brand','model','serial_number','purchase_date','purchase_price','currency','location'] as const).map(k=><label key={k}>{k.replaceAll('_',' ')}<input type={k==='purchase_date'?'date':k==='purchase_price'?'number':'text'} value={asset[k]} onChange={e=>setAsset(v=>({...v,[k]:e.target.value}))} required={k==='name'}/></label>)}<button>Add asset</button></form>{goods.map(a=><article className="finance-row" key={a.id}><div><b>{a.name}</b><small>{a.brand} {a.model} · {a.serial_number}</small>{a.warranties.map(w=><small key={w.id}>Warranty: {w.provider}, expires {w.end_date}</small>)}{a.maintenance.map(m=><small key={m.id}>Maintenance: {m.title}, due {m.next_due_date}</small>)}</div><div className="actions"><button className="secondary" onClick={()=>{const name=prompt('Asset name',a.name);if(name)void act(finance.editAsset(a.id,{name}),'Asset updated');}}>Rename</button><button className="secondary" onClick={()=>{const provider=prompt('Warranty provider');const start_date=prompt('Start date YYYY-MM-DD');const end_date=prompt('Expiry YYYY-MM-DD');if(provider&&start_date&&end_date)void act(finance.addWarranty(a.id,{provider,start_date,end_date}),'Warranty saved');}}>Add warranty</button><button className="secondary" onClick={()=>{const title=prompt('Maintenance task');const next_due_date=prompt('Next date YYYY-MM-DD');if(title&&next_due_date)void act(finance.addMaintenance(a.id,{title,next_due_date}),'Maintenance saved');}}>Schedule maintenance</button><button className="danger" onClick={()=>{if(confirm('Delete this asset?'))void act(finance.deleteAsset(a.id),'Asset deleted');}}>Delete</button></div></article>)}</section>}
 {tab==='receipt'&&<section className="card"><h2>Reviewed receipt import</h2>{documentId?<><p>Document #{documentId}</p>{suggestion?.eligible?<><p>{suggestion.merchant_name}: {suggestion.currency} {suggestion.amount} on {suggestion.expense_date}</p><p>No expense is created until you confirm.</p><button onClick={()=>void act(finance.acceptReceipt(documentId),'Reviewed receipt imported')}>Confirm and create expense</button></>:<p>{suggestion?.reason??'Checking reviewed extraction…'}</p>}</>:<p>Open this tab from a document using <code>/finance?document_id=DOCUMENT_ID</code>.</p>}</section>}
 </main>;
}
