<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('calendar_connections',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->string('provider',40);$t->string('external_calendar_id')->nullable();$t->text('access_token')->nullable();$t->text('refresh_token')->nullable();$t->timestampTz('token_expires_at')->nullable();$t->json('scopes')->nullable();$t->string('status',25)->default('disconnected');$t->timestampTz('authorized_at')->nullable();$t->timestamps();$t->unique(['user_id','household_id','provider']);});
  Schema::create('calendar_events',function(Blueprint $t){$t->id();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('task_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('document_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('calendar_connection_id')->nullable()->constrained()->nullOnDelete();$t->string('external_event_id')->nullable();$t->string('title');$t->text('description')->nullable();$t->string('location')->nullable();$t->dateTimeTz('starts_at');$t->dateTimeTz('ends_at');$t->string('timezone',64)->default('UTC');$t->string('status',20)->default('confirmed');$t->json('reminder_offsets')->nullable();$t->string('recurrence_frequency',12)->nullable();$t->unsignedSmallInteger('recurrence_interval')->default(1);$t->dateTimeTz('recurrence_until')->nullable();$t->string('series_key',64)->nullable();$t->dateTimeTz('occurrence_at')->nullable();$t->timestamps();$t->softDeletes();$t->index(['household_id','starts_at','ends_at']);$t->unique(['series_key','occurrence_at']);});
  Schema::create('notification_templates',function(Blueprint $t){$t->id();$t->string('key')->unique();$t->string('locale',12)->default('en');$t->string('title_template');$t->text('body_template');$t->json('channels');$t->boolean('enabled')->default(true);$t->timestamps();});
  Schema::create('life_notifications',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->foreignId('calendar_event_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('task_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('reminder_id')->nullable()->constrained('reminders')->nullOnDelete();$t->string('type',55);$t->string('title');$t->text('body');$t->json('payload')->nullable();$t->string('priority',12)->default('normal');$t->string('status',20)->default('pending');$t->string('dedupe_key',100);$t->dateTimeTz('scheduled_at');$t->dateTimeTz('read_at')->nullable();$t->dateTimeTz('delivered_at')->nullable();$t->timestamps();$t->unique(['user_id','dedupe_key']);$t->index(['status','scheduled_at']);});
  Schema::create('notification_deliveries',function(Blueprint $t){$t->id();$t->foreignId('notification_id')->constrained('life_notifications')->cascadeOnDelete();$t->string('channel',20);$t->string('status',20)->default('pending');$t->unsignedSmallInteger('attempts')->default(0);$t->dateTimeTz('next_attempt_at')->nullable();$t->dateTimeTz('delivered_at')->nullable();$t->text('last_error')->nullable();$t->string('provider_reference')->nullable();$t->timestamps();$t->unique(['notification_id','channel']);$t->index(['status','next_attempt_at']);});
  Schema::create('browser_push_subscriptions',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->text('endpoint');$t->char('endpoint_hash',64)->unique();$t->text('p256dh');$t->text('auth_secret');$t->timestampTz('last_seen_at')->nullable();$t->timestamps();});
  Schema::create('notification_settings',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->time('quiet_start')->nullable();$t->time('quiet_end')->nullable();$t->string('timezone',64)->default('UTC');$t->boolean('browser_enabled')->default(false);$t->boolean('in_app_enabled')->default(true);$t->boolean('escalation_enabled')->default(true);$t->timestamps();});
 }
 public function down():void{foreach(['notification_settings','browser_push_subscriptions','notification_deliveries','life_notifications','notification_templates','calendar_events','calendar_connections'] as $t)Schema::dropIfExists($t);}
};
