<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::create('profiles',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->string('first_name')->nullable();$t->string('last_name')->nullable();$t->string('phone',30)->nullable();$t->date('date_of_birth')->nullable();$t->string('locale',12)->default('en');$t->timestamps();});
 Schema::create('households',function(Blueprint $t){$t->id();$t->string('name');$t->timestamps();});
 Schema::create('household_members',function(Blueprint $t){$t->id();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('role',30);$t->timestamps();$t->unique(['household_id','user_id']);$t->index(['user_id','role']);});
 Schema::create('notification_preferences',function(Blueprint $t){$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->boolean('email_enabled')->default(true);$t->boolean('push_enabled')->default(true);$t->boolean('reminder_enabled')->default(true);$t->boolean('digest_enabled')->default(false);$t->timestamps();});
 Schema::create('integration_connections',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('provider',60);$t->string('provider_account_id')->nullable();$t->string('status',30)->default('disconnected');$t->json('scopes')->nullable();$t->text('encrypted_credentials')->nullable();$t->timestamp('connected_at')->nullable();$t->timestamp('last_synced_at')->nullable();$t->timestamps();$t->unique(['user_id','provider','provider_account_id']);});
 Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('household_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('actor_user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('event',120)->index();$t->string('auditable_type')->nullable();$t->unsignedBigInteger('auditable_id')->nullable();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->json('metadata')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['auditable_type','auditable_id']);$t->index(['household_id','created_at']);});
 }public function down():void{Schema::dropIfExists('audit_logs');Schema::dropIfExists('integration_connections');Schema::dropIfExists('notification_preferences');Schema::dropIfExists('household_members');Schema::dropIfExists('households');Schema::dropIfExists('profiles');}};
