<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::create('expense_categories',function(Blueprint $t){$t->id();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('slug');$t->decimal('monthly_budget',15,2)->nullable();$t->timestamps();$t->unique(['household_id','slug']);});
  Schema::create('merchants',function(Blueprint $t){$t->id();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('normalized_name');$t->timestamps();$t->unique(['household_id','normalized_name']);});
  Schema::create('asset_categories',function(Blueprint $t){$t->id();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('slug');$t->timestamps();$t->unique(['household_id','slug']);});
  Schema::create('subscriptions',function(Blueprint $t){$t->id();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('document_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('merchant_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('provider');$t->decimal('price',15,2);$t->char('currency',3);$t->string('billing_cycle',20);$t->date('next_billing_date');$t->string('renewal_type',30)->default('automatic');$t->date('cancellation_deadline')->nullable();$t->string('status',20)->default('active');$t->decimal('previous_price',15,2)->nullable();$t->timestamp('last_price_change_at')->nullable();$t->char('dedupe_key',64);$t->date('last_generated_billing_date')->nullable();$t->foreignId('reminder_task_id')->nullable()->constrained('tasks')->nullOnDelete();$t->timestamps();$t->softDeletes();$t->unique(['household_id','dedupe_key']);$t->index(['household_id','status','next_billing_date']);});
  Schema::create('expenses',function(Blueprint $t){$t->id();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('expense_category_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('merchant_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('document_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('receipt_extraction_id')->nullable()->constrained('document_extractions')->nullOnDelete();$t->foreignId('subscription_id')->nullable()->constrained()->nullOnDelete();$t->string('title');$t->text('description')->nullable();$t->decimal('amount',15,2);$t->char('currency',3);$t->date('expense_date');$t->string('source',20)->default('manual');$t->char('import_hash',64)->nullable();$t->string('recurrence_cycle',20)->nullable();$t->date('next_occurrence_date')->nullable();$t->timestamps();$t->softDeletes();$t->index(['household_id','currency','expense_date']);$t->unique(['household_id','receipt_extraction_id']);$t->unique(['household_id','import_hash']);});
  Schema::create('subscription_payments',function(Blueprint $t){$t->id();$t->foreignId('subscription_id')->constrained()->cascadeOnDelete();$t->foreignId('expense_id')->nullable()->constrained()->nullOnDelete();$t->decimal('amount',15,2);$t->char('currency',3);$t->date('billing_date');$t->string('source',20)->default('confirmed');$t->timestamps();$t->unique(['subscription_id','billing_date']);});
  Schema::create('assets',function(Blueprint $t){$t->id();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('asset_category_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('merchant_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('document_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('brand')->nullable();$t->string('model')->nullable();$t->string('serial_number')->nullable();$t->date('purchase_date')->nullable();$t->decimal('purchase_price',15,2)->nullable();$t->char('currency',3)->nullable();$t->string('location')->nullable();$t->string('status',20)->default('owned');$t->timestamps();$t->softDeletes();$t->index(['household_id','serial_number']);});
  Schema::create('warranties',function(Blueprint $t){$t->id();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->foreignId('asset_id')->constrained()->cascadeOnDelete();$t->string('provider');$t->date('start_date');$t->date('end_date');$t->text('coverage_notes')->nullable();$t->foreignId('proof_document_id')->nullable()->constrained('documents')->nullOnDelete();$t->string('status',20)->default('active');$t->foreignId('reminder_task_id')->nullable()->constrained('tasks')->nullOnDelete();$t->timestamps();$t->index(['household_id','end_date']);});
  Schema::create('maintenance_records',function(Blueprint $t){$t->id();$t->foreignId('household_id')->constrained()->cascadeOnDelete();$t->foreignId('asset_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('notes')->nullable();$t->date('performed_at')->nullable();$t->date('next_due_date')->nullable();$t->decimal('cost',15,2)->nullable();$t->char('currency',3)->nullable();$t->foreignId('document_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('reminder_task_id')->nullable()->constrained('tasks')->nullOnDelete();$t->timestamps();$t->index(['household_id','next_due_date']);});
 }
 public function down():void {foreach(['maintenance_records','warranties','assets','subscription_payments','expenses','subscriptions','asset_categories','merchants','expense_categories'] as $table)Schema::dropIfExists($table);}
};
