import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {addEvent,editEvent,deleteEvent,events,googleStatus,googleConnect,googleDisconnect,googleExport,fromTask,fromDocument} from './calendarApi';
import type {CalendarEvent} from './types';
type View='day'|'week'|'month';
const dateOnly=(d:Date)=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
function localInput(d:Date){const t=new Date(d.getTime()-d.getTimezoneOffset()*60000);return t.toISOString().slice(0,16)}
export function CalendarPage(){
 const [params]=useSearchParams();const [view,setView]=useState<View>('month');const [cursor,setCursor]=useState(new Date());const [items,setItems]=useState<CalendarEvent[]>([]);const [chosen,setChosen]=useState<CalendarEvent|null>(null);const [msg,setMsg]=useState('');const [google,setGoogle]=useState('disconnected');const [loading,setLoading]=useState(false);
 const [form,setForm]=useState({title:'',description:'',location:'',starts_at:localInput(new Date(Date.now()+3600000)),ends_at:localInput(new Date(Date.now()+7200000)),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',recurrence_frequency:'',recurrence_interval:'1',recurrence_until:'',reminder_offsets:'7,1,0'});
 const range=useMemo(()=>{const begin=new Date(cursor);if(view==='month'){begin.setDate(1);begin.setDate(begin.getDate()-begin.getDay());}else if(view==='week'){begin.setDate(begin.getDate()-begin.getDay());}begin.setHours(0,0,0,0);const end=new Date(begin);end.setDate(begin.getDate()+(view==='month'?42:view==='week'?7:1));return {begin,end};},[cursor,view]);
 const refresh=async()=>{try{setLoading(true);setItems(await events(range.begin.toISOString(),range.end.toISOString()));setMsg('');}catch(e:any){setMsg(e.friendlyMessage??'Could not load calendar');}finally{setLoading(false)}};
 useEffect(()=>{void refresh();},[range.begin.getTime(),range.end.getTime()]);
 useEffect(()=>{void googleStatus().then(r=>setGoogle(r.connection?.status||'disconnected')).catch(()=>{});},[]);
 const asForm=(event:CalendarEvent)=>{setChosen(event);setForm({...form,title:event.title,description:event.description??'',location:event.location??'',starts_at:localInput(new Date(event.starts_at)),ends_at:localInput(new Date(event.ends_at)),timezone:event.timezone,recurrence_frequency:'',recurrence_until:'',reminder_offsets:(event.reminder_offsets??[]).join(',')});};
 const submit=async(e:FormEvent)=>{e.preventDefault();try{setLoading(true);const body={...form,starts_at:form.starts_at,ends_at:form.ends_at,recurrence_frequency:form.recurrence_frequency||null,recurrence_interval:Number(form.recurrence_interval),recurrence_until:form.recurrence_until||null,reminder_offsets:form.reminder_offsets.split(',').map(x=>Number(x.trim())).filter(Number.isFinite)};if(chosen)await editEvent(chosen.id,body);else await addEvent(body);setChosen(null);await refresh();}catch(e:any){if(e?.response?.status===409){const conflicts=e.response.data?.error?.details?.conflicts??[];if(window.confirm(`Overlapping events: ${conflicts.map((c:{title:string})=>c.title).join(', ')}. Save anyway?`)){const body={...form,recurrence_frequency:form.recurrence_frequency||null,recurrence_until:form.recurrence_until||null,recurrence_interval:Number(form.recurrence_interval),reminder_offsets:form.reminder_offsets.split(',').map(Number),confirm_conflicts:true};try{if(chosen)await editEvent(chosen.id,body);else await addEvent(body);await refresh();}catch(err:any){setMsg(err.friendlyMessage??'Save failed');}}}else setMsg(e.friendlyMessage??'Save failed');}finally{setLoading(false)}};
 const shift=(direction:number)=>{const d=new Date(cursor);if(view==='month')d.setMonth(d.getMonth()+direction);else d.setDate(d.getDate()+direction*(view==='week'?7:1));setCursor(d)};
 const cells=Array.from({length:view==='month'?42:view==='week'?7:1},(_,i)=>{const d=new Date(range.begin);d.setDate(range.begin.getDate()+i);return d;});
 const dayEvents=(day:Date)=>items.filter(e=>dateOnly(new Date(e.starts_at))===dateOnly(day));
 const quick=async()=>{const taskId=params.get('task_id'),documentId=params.get('document_id');const run=async(confirm_conflicts:boolean)=>{if(taskId)await fromTask(Number(taskId),form.timezone,60,confirm_conflicts);else if(documentId)await fromDocument(Number(documentId),{title:form.title,starts_at:form.starts_at,ends_at:form.ends_at,timezone:form.timezone,confirm_conflicts});await refresh();};try{await run(false);}catch(e:any){if(e.response?.status===409&&window.confirm('Linked event overlaps another event. Create it anyway?')){try{await run(true);}catch(err:any){setMsg(err.friendlyMessage??'Could not create linked event');}}else setMsg(e.friendlyMessage??'Could not create linked event');}};
 return <main className="page p6-page"><header><div><h1>Calendar</h1><p>Internal scheduling and explicit external sync</p></div><div className="actions"><Link className="button-link" to="/notifications">Notifications</Link><Link className="button-link" to="/">Dashboard</Link></div></header>
 {msg&&<div className="error" role="alert">{msg}</div>}
 <section className="card"><div className="actions wrap"><button type="button" className="secondary" onClick={()=>shift(-1)}>Previous</button><strong>{cursor.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong><button type="button" className="secondary" onClick={()=>shift(1)}>Next</button><button type="button" className="secondary" onClick={()=>setCursor(new Date())}>Today</button>{(['day','week','month'] as View[]).map(v=><button type="button" className={view===v?'':'secondary'} key={v} onClick={()=>setView(v)}>{v}</button>)}</div><div className={`p6-calendar p6-${view}`}>{cells.map(day=><section className="p6-day" key={dateOnly(day)}><b>{day.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</b>{dayEvents(day).map(e=><button key={e.id} type="button" className="p6-event secondary" onClick={()=>asForm(e)}>{new Date(e.starts_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} {e.title}</button>)}</section>)}</div>{loading&&<p>Loading…</p>}</section>
 <div className="grid"><form className="card" onSubmit={submit}><h2>{chosen?'Edit event':'Create event'}</h2><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Start<input required type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>End<input required type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label><label>Timezone<input required value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label>{!chosen&&<><label>Recurrence<select value={form.recurrence_frequency} onChange={e=>setForm({...form,recurrence_frequency:e.target.value})}><option value="">None</option>{['daily','weekly','monthly','yearly'].map(v=><option key={v}>{v}</option>)}</select></label>{form.recurrence_frequency&&<><label>Repeat every<input type="number" min="1" max="365" value={form.recurrence_interval} onChange={e=>setForm({...form,recurrence_interval:e.target.value})}/></label><label>Repeat until<input type="datetime-local" value={form.recurrence_until} onChange={e=>setForm({...form,recurrence_until:e.target.value})}/></label></>}</>}<label>Reminder offsets (days)<input value={form.reminder_offsets} onChange={e=>setForm({...form,reminder_offsets:e.target.value})}/></label><div className="actions wrap"><button disabled={loading}>{chosen?'Save event':'Create event'}</button>{chosen&&<><button type="button" className="secondary" onClick={()=>{setChosen(null);setMsg('')}}>Cancel edit</button><button type="button" className="danger" onClick={async()=>{if(window.confirm('Delete this occurrence?')){await deleteEvent(chosen.id);setChosen(null);await refresh()}}}>Delete</button></>}</div></form>
 <section className="card"><h2>Google Calendar</h2><p>Connection: {google}</p><p>Only connect or export when you explicitly authorize it. Automatic outbound sync is disabled.</p>{google!=='connected'?<button type="button" onClick={()=>void googleConnect().catch((e:any)=>setMsg(e.friendlyMessage??'Google credentials not configured'))}>Connect Google</button>:<button type="button" className="secondary" onClick={async()=>{await googleDisconnect();setGoogle('disconnected')}}>Disconnect</button>}{chosen&&google==='connected'&&!chosen.external_event_id&&<button type="button" onClick={async()=>{try{await googleExport(chosen.id);setMsg('Exported to Google Calendar.')}catch(e:any){setMsg(e.friendlyMessage??'Export failed')}}}>Export selected event</button>}{(params.get('task_id')||params.get('document_id'))&&<div><h3>Linked event</h3><p>Confirm the title, date and timezone above before creating.</p><button type="button" onClick={()=>void quick()}>Create linked event</button></div>}</section></div></main>
}
