import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {getNotificationSettings,markRead,notices,saveNotificationSettings} from './calendarApi';
import type {LifeNotification} from './types';
import type {NotificationSettings} from './calendarApi';
import {listenForLifePilotUpdates} from './realtime';
export function NotificationsPage(){const [items,setItems]=useState<LifeNotification[]>([]);const [settings,setSettings]=useState<NotificationSettings|null>(null);const [message,setMessage]=useState('');const [permission,setPermission]=useState(typeof Notification==='undefined'?'unsupported':Notification.permission);
 const reload=async()=>{try{setItems(await notices());}catch(e:any){setMessage(e.friendlyMessage??'Could not load notifications')}};
 useEffect(()=>{void reload();void getNotificationSettings().then(setSettings).catch(()=>{});const timer=window.setInterval(()=>void reload(),60000);let stop=()=>{};let active=true;void listenForLifePilotUpdates(event=>{void reload();if(event.kind==='reminder.created'&&permission==='granted'&&settings?.browser_enabled&&typeof Notification!=='undefined')new Notification(event.data?.title||'LifePilot reminder');}).then(fn=>{if(active)stop=fn;else fn();});return ()=>{active=false;window.clearInterval(timer);stop()};},[permission,settings?.browser_enabled]);
 const save=async()=>{if(!settings)return;try{setSettings(await saveNotificationSettings(settings));setMessage('Settings saved.')}catch(e:any){setMessage(e.friendlyMessage??'Could not save')}};
 const enable=async()=>{if(typeof Notification==='undefined'){setMessage('Browser notifications not supported.');return;}const v=await Notification.requestPermission();setPermission(v);if(v==='granted'&&settings)setSettings({...settings,browser_enabled:true});};
 return <main className="page p6-page"><header><div><h1>Notifications</h1><p>Delivery inbox and personal preferences</p></div><Link className="button-link" to="/calendar">Calendar</Link></header>{message&&<p role="status">{message}</p>}<div className="grid"><section className="card"><h2>Inbox</h2><button className="secondary" type="button" onClick={()=>void reload()}>Refresh</button>{items.map(n=><article key={n.id} className="p6-notice"><div><strong>{n.title}</strong>{!n.read_at&&<span className="badge">Unread</span>}</div><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString()} · {n.priority}</small>{n.deliveries?.map(d=><span key={d.channel} className="badge">{d.channel}: {d.status}</span>)}{!n.read_at&&<button type="button" className="secondary" onClick={async()=>{await markRead(n.id);await reload()}}>Mark read</button>}</article>)}{items.length===0&&<p>No notifications yet.</p>}</section><section className="card"><h2>Quiet hours</h2>{settings&&<><label>Timezone<input value={settings.timezone} onChange={e=>setSettings({...settings,timezone:e.target.value})}/></label><label>Quiet from<input type="time" value={settings.quiet_start?.slice(0,5)||''} onChange={e=>setSettings({...settings,quiet_start:e.target.value||null})}/></label><label>Quiet until<input type="time" value={settings.quiet_end?.slice(0,5)||''} onChange={e=>setSettings({...settings,quiet_end:e.target.value||null})}/></label>{(['browser_enabled','in_app_enabled','escalation_enabled'] as const).map(key=><label className="check" key={key}><input type="checkbox" checked={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/>{key.replaceAll('_',' ')}</label>)}<button type="button" onClick={()=>void save()}>Save notification settings</button><button type="button" className="secondary" onClick={()=>void enable()}>Allow browser notifications ({permission})</button><p>Emails use your existing Settings → Notifications preference. Browser alerts require this tab to be connected; background push requires a configured delivery adapter.</p></>}</section></div></main>}
